Update sample.yml

diff --git a/.github/workflows/sample.yml b/.github/workflows/sample.yml
--- a/.github/workflows/sample.yml
+++ b/.github/workflows/sample.yml
@@ -1,50 +1,56 @@
-name: Deploy Flask App with Virtualenv
+name: Deploy Flask App
 
 on:
   push:
-    branches: [main]
-  workflow_dispatch:
+    branches:
+      - main
+
+env:
+  HEALTHCHECK_URL: http://35.154.189.47:50000
 
 jobs:
-  deploy:
+  Build-test-deploy:
     runs-on: self-hosted
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - name: Checkout Code
+        uses: actions/checkout@v3
 
       - name: Set up Python
-        uses: actions/setup-python@v5
+        uses: actions/setup-python@v4
         with:
-          python-version: '3.10'
+          python-version: '3.9'
 
-      - name: Create and activate virtual environment
+      - name: Virtual env
         run: |
-          python -m venv venv
+          sudo apt install python3.12-venv -y
+          python3 -m venv venv
           source venv/bin/activate
+          
+      - name: Install Dependencies
+        run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
-      
-          script: |
-            pkill -f app.py || true
-            cd /home/ubuntu/flask-gha-deploy
-            python3 -m venv venv
-            source venv/bin/activate
-            pip install -r requirements.txt
-            nohup venv/bin/python app.py > flask.log 2>&1 &
+      - name: Run Unit Tests
+        run: |
+          python3 -m unittest test_app.py
+          
+      - name: Deploy Flask Application
+        run: |
+          nohup python3 app.py &
 
-  health-check:
+  health:
+    needs: Build-test-deploy
     runs-on: self-hosted
-    needs: deploy
 
     steps:
-      - name: Check Flask App Health
+      - name: Health check
         run: |
-          echo "Waiting for app to start..."
-          sleep 5
-          curl -f http://${{ secrets.SERVER_HOST }}:5000 || {
-            echo "❌ Health check failed!"
-            exit 1
-          }
-          echo "✅ Health check passed!"
+          for i in {1..10}; do
+            curl -s -o /dev/null -w "%{http_code}" $HEALTHCHECK_URL | grep "200" && echo "Health check passed" && exit 0 || echo "Waiting for service...";
+            sleep 5;
+          done;
+          echo "Health check failed***" && exit 1
+          
+          
